apiVersion: v1
data:
  default.oracle-instance-host-pg: 192.168.2.38
  default.oracle-instance-port-pg: "1521"
  default.oracle-instance-user-pg: parametrageglobal
kind: ConfigMap
metadata:

  name: oracle-config-pg
  namespace: default
